spring.application.name=jwtTokenSpring
spring.config.import=application_production.properties
spring.profiles.active=dev

spring.jpa.show-sql=true

server.port=9090

spring.datasource.url=jdbc:mysql://localhost/springSecurity

spring.datasource.driverClassName=com.mysql.jdbc.Driver

spring.datasource.username=root

spring.datasource.password=somesh

server.servlet.session.timeout=20m
